# -*- coding: utf-8 -*-
"""MediaAlunos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qHBpQ-NxYlqaeYk3BUxwdCZhaO-FkMKX
"""

Um aluno vai receber três notas de forma dinamica, por entrada de dados, e se  o aluno tirar entre
10 e 7 de média ele será aprovado, senão, se o aluno tirar menos do que 7  e mais do que  4 ele
ainda vai para a final, senão o aluno reprova automaticamente.A sáida de dados deve conter
a média do aluno e a sua situação de acordo com a sua média.

nota1 = float(input( 'Nota 1:'))
nota2 = float(input( 'Nota 2:'))
nota3 = float(input( 'Nota 3:'))
media = (nota1 + nota2 + nota3) / 3  
print("A media desse estudante foi",media) 
if media >=7:
    sit= 'aprovado'
elif media >4:
    sit ='em recuperação'
else:
    sit = 'reprovado'
print(f'O aluno está {sit} com média {media:.2f}')